from selenium import webdriver
from selenium.webdriver.common.keys import Keys

import time

fp = webdriver.FirefoxProfile(
    "C:\\Users\\Thomas\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\31wtuwdv.default-release")
driver = webdriver.Firefox(firefox_profile=fp)
driver.get("https://www.instagram.com/callofduty/")
time.sleep(10)
element = driver.find_element_by_xpath("//main[contains(@class,'o64aR')]//li[2]//a[1]")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[1]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[2]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[3]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[4]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[5]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[6]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[7]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[8]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[9]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[10]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[11]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[12]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[13]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[14]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[15]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[16]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[17]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[18]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[19]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[20]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[21]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[22]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[23]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[24]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[25]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[26]/div[1]/div[2]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[27]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[28]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[29]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[30]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[31]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[32]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[33]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[34]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[35]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[36]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[37]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[38]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[39]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[40]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[41]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[42]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[43]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[44]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[45]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[46]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[47]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[48]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[49]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[50]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[51]/div[1]/div[3]/button[1]")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/ul[1]/div[1]/li[52]/div[1]/div[3]/button[1]")
element.click()

